"""Expanded resource and resource_group to have top-level links

Revision ID: 249635ae0402
Revises: 571d7703b7ab
Create Date: 2022-08-25 10:02:48.483578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249635ae0402'
down_revision = '571d7703b7ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_group', sa.Column('is_top_level', sa.Boolean(), server_default='false', nullable=False), schema='resource_allocator')
    op.add_column('resource_group', sa.Column('top_resource_group_id', sa.Integer(), nullable=True), schema='resource_allocator')
    op.create_foreign_key(None, 'resource_group', 'resource_group', ['top_resource_group_id'], ['id'], source_schema='resource_allocator', referent_schema='resource_allocator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource_group', schema='resource_allocator', type_='foreignkey')
    op.drop_column('resource_group', 'top_resource_group_id', schema='resource_allocator')
    op.drop_column('resource_group', 'is_top_level', schema='resource_allocator')
    # ### end Alembic commands ###
