"""Fixed incorrect base model column name

Revision ID: 571d7703b7ab
Revises: b23a9cbcc883
Create Date: 2022-08-24 22:20:37.730922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '571d7703b7ab'
down_revision = 'b23a9cbcc883'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocation', sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False), schema='resource_allocator')
    op.drop_column('allocation', 'created_date', schema='resource_allocator')
    op.add_column('iteration', sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False), schema='resource_allocator')
    op.drop_column('iteration', 'created_date', schema='resource_allocator')
    op.add_column('request', sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False), schema='resource_allocator')
    op.drop_column('request', 'created_date', schema='resource_allocator')
    op.add_column('resource', sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False), schema='resource_allocator')
    op.drop_column('resource', 'created_date', schema='resource_allocator')
    op.add_column('resource_group', sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False), schema='resource_allocator')
    op.drop_column('resource_group', 'created_date', schema='resource_allocator')
    op.add_column('resource_to_group', sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False), schema='resource_allocator')
    op.drop_column('resource_to_group', 'created_date', schema='resource_allocator')
    op.add_column('role', sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False), schema='resource_allocator')
    op.drop_column('role', 'created_date', schema='resource_allocator')
    op.add_column('user', sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False), schema='resource_allocator')
    op.drop_column('user', 'created_date', schema='resource_allocator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='resource_allocator')
    op.drop_column('user', 'created_time', schema='resource_allocator')
    op.add_column('role', sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='resource_allocator')
    op.drop_column('role', 'created_time', schema='resource_allocator')
    op.add_column('resource_to_group', sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='resource_allocator')
    op.drop_column('resource_to_group', 'created_time', schema='resource_allocator')
    op.add_column('resource_group', sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='resource_allocator')
    op.drop_column('resource_group', 'created_time', schema='resource_allocator')
    op.add_column('resource', sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='resource_allocator')
    op.drop_column('resource', 'created_time', schema='resource_allocator')
    op.add_column('request', sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='resource_allocator')
    op.drop_column('request', 'created_time', schema='resource_allocator')
    op.add_column('iteration', sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='resource_allocator')
    op.drop_column('iteration', 'created_time', schema='resource_allocator')
    op.add_column('allocation', sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='resource_allocator')
    op.drop_column('allocation', 'created_time', schema='resource_allocator')
    # ### end Alembic commands ###
