"""Added user fields and constraints

Revision ID: 720cdb41038a
Revises: c0788d6869bb
Create Date: 2022-08-24 09:59:01.771205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720cdb41038a'
down_revision = 'c0788d6869bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role', ['role'], schema='resource_allocator')
    op.add_column('user', sa.Column('first_name', sa.String(length=255), nullable=False), schema='resource_allocator')
    op.add_column('user', sa.Column('last_name', sa.String(length=255), nullable=False), schema='resource_allocator')
    op.create_unique_constraint(None, 'user', ['email'], schema='resource_allocator')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'], source_schema='resource_allocator', referent_schema='resource_allocator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='resource_allocator', type_='foreignkey')
    op.drop_constraint(None, 'user', schema='resource_allocator', type_='unique')
    op.drop_column('user', 'last_name', schema='resource_allocator')
    op.drop_column('user', 'first_name', schema='resource_allocator')
    op.drop_constraint(None, 'role', schema='resource_allocator', type_='unique')
    # ### end Alembic commands ###
