"""Changed iteration columns to date

Revision ID: 9fb8acb8ff83
Revises: 35654575f599
Create Date: 2022-08-25 13:24:50.691351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fb8acb8ff83'
down_revision = '35654575f599'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iteration', sa.Column('start_date', sa.Date(), nullable=False), schema='resource_allocator')
    op.add_column('iteration', sa.Column('end_date', sa.Date(), nullable=False), schema='resource_allocator')
    op.drop_column('iteration', 'start_time', schema='resource_allocator')
    op.drop_column('iteration', 'end_time', schema='resource_allocator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iteration', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='resource_allocator')
    op.add_column('iteration', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='resource_allocator')
    op.drop_column('iteration', 'end_date', schema='resource_allocator')
    op.drop_column('iteration', 'start_date', schema='resource_allocator')
    # ### end Alembic commands ###
