"""Added resource tables

Revision ID: b23a9cbcc883
Revises: 720cdb41038a
Create Date: 2022-08-24 12:14:02.689016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23a9cbcc883'
down_revision = '720cdb41038a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_to_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_group_id'], ['resource_allocator.resource_group.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_allocator.resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='resource_allocator'
    )
    op.add_column('resource', sa.Column('name', sa.String(length=255), nullable=False), schema='resource_allocator')
    op.add_column('resource', sa.Column('top_resource_group_id', sa.Integer(), nullable=True), schema='resource_allocator')
    op.create_unique_constraint(None, 'resource', ['name'], schema='resource_allocator')
    op.create_foreign_key(None, 'resource', 'resource_group', ['top_resource_group_id'], ['id'], source_schema='resource_allocator', referent_schema='resource_allocator')
    op.add_column('resource_group', sa.Column('name', sa.String(length=255), nullable=False), schema='resource_allocator')
    op.create_unique_constraint(None, 'resource_group', ['name'], schema='resource_allocator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource_group', schema='resource_allocator', type_='unique')
    op.drop_column('resource_group', 'name', schema='resource_allocator')
    op.drop_constraint(None, 'resource', schema='resource_allocator', type_='foreignkey')
    op.drop_constraint(None, 'resource', schema='resource_allocator', type_='unique')
    op.drop_column('resource', 'top_resource_group_id', schema='resource_allocator')
    op.drop_column('resource', 'name', schema='resource_allocator')
    op.drop_table('resource_to_group', schema='resource_allocator')
    # ### end Alembic commands ###
